In [24]:
# Importing Libraries
import selenium
import pandas as pd
import requests
import time
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver import ActionChains ##To select fixtures
from selenium.webdriver.common import keys

In [34]:
driver = webdriver.Chrome(r"C:\Users\Arvind\chromedriver.exe") ### installing Chrome driver.
time.sleep(2)

In [64]:
url  = 'https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos'
driver.get(url)
time.sleep(2)

Rank = []
rank = driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[1]')
for i in rank[:30]:
    Rank.append(i.text.replace(".",""))
print(len(Rank))

Name = []
for i in driver.find_elements_by_xpath('//div[@class="mw-parser-output"]/table[3]/tbody/tr/td[2]'):
    Name.append(i.text)
print(len(Name))

Artist = []
for i in driver.find_elements_by_xpath('//div[@class="mw-parser-output"]/table[3]/tbody/tr/td[3]'):
    Artist.append(i.text)
print(len(Artist))

Uploaded = []
for i in driver.find_elements_by_xpath('//div[@class="mw-parser-output"]/table[3]/tbody/tr/td[5]'):
    Uploaded.append(i.text)
print(len(Uploaded))

Views = []
for i in driver.find_elements_by_xpath('//div[@class="mw-parser-output"]/table[3]/tbody/tr/td[4]'):
    Views.append(i.text)
print(len(Views))

df = pd.DataFrame({})
df['Rank'] = Rank
df['Name'] =  Name
df['Artist'] = Artist
df['Upload date'] = Uploaded
df['Views'] = Views
df

30
30
30
30
30

,Rank,Name,Artist,Upload date,Views
0,1,"""Baby Shark Dance""[23]",Pinkfong Kids' Songs & Stories,"June 17, 2016",9.27
1,2,"""Despacito""[25]",Luis Fonsi,"January 12, 2017",7.52
2,3,"""Johny Johny Yes Papa""[26]",LooLoo Kids,"October 8, 2016",5.68
3,4,"""Shape of You""[27]",Ed Sheeran,"January 30, 2017",5.45
4,5,"""See You Again""[28]",Wiz Khalifa,"April 6, 2015",5.25
5,6,"""Bath Song""[31]",Cocomelon – Nursery Rhymes,"May 2, 2018",4.49
6,7,"""Learning Colors – Colorful Eggs on a Farm""[32]",Miroshka TV,"February 27, 2018",4.46
7,8,"""Masha and the Bear – Recipe for Disaster""[33]",Get Movies,"January 31, 2012",4.46
8,9,"""Uptown Funk""[34]",Mark Ronson,"November 19, 2014",4.28
9,10,"""Gangnam Style""[35]",Psy,"July 15, 2012",4.18
10,11,"""Phonics Song with Two Words""[37]",ChuChu TV,"March 6, 2014",4.14
11,12,"""Dame Tu Cosita""[38]",El Chombo,"April 5, 2018",3.57
12,13,"""Sugar""[39]",Maroon 5,"January 14, 2015",3.54
13,14,"""Sorry""[40]",Justin Bieber,"October 22, 2015",3.46
14,15,"""Roar""[41]",Katy Perry,"September 5, 2013",3.42
15,16,"""Counting Stars""[42]",OneRepublic,"May 31, 2013",3.38
16,17,"""Thinking Out Loud""[43]",Ed Sheeran,"October 7, 2014",3.31
17,18,"""Wheels on the Bus""[44]",Cocomelon – Nursery Rhymes,"May 24, 2018",3.24
18,19,"""Dark Horse""[45]",Katy Perry,"February 20, 2014",3.14
19,20,"""Faded""[46]",Alan Walker,"December 3, 2015",3.13
20,21,"""Girls Like You""[47]",Maroon 5,"May 31, 2018",3.11
21,22,"""Shake It Off""[48]",Taylor Swift,"August 18, 2014",3.09
22,23,"""Lean On""[49]",Major Lazer,"March 22, 2015",3.09
23,24,"""Bailando""[50]",Enrique Iglesias,"April 11, 2014",3.09
24,25,"""Let Her Go""[51]",Passenger,"July 25, 2012",3.07
25,26,"""Axel F""[52]",Crazy Frog,"June 16, 2009",2.98
26,27,"""Mi Gente""[53]",J Balvin,"June 29, 2017",2.97
27,28,"""Perfect""[54]",Ed Sheeran,"November 9, 2017",2.94
28,29,"""Waka Waka (This Time for Africa)""[55]",Shakira,"June 4, 2010",2.93
29,30,"""Hello""[56]",Adele,"October 22, 2015",2.88

_____________________________________________________End ________________________________________________________________

In [81]:
driver.get('https://www.bcci.tv/')
time.sleep(2)
action = ActionChains(driver)
international = driver.find_element_by_xpath('//div[@class="navigation__link navigation__link--has-drop-down js-navigation-link"]')
fixtures = driver.find_element_by_xpath('//div[@class="navigation__drop-down drop-down drop-down--reveal-on-hover"]/div/ul/li/a')
action.move_to_element(international).click(fixtures).perform()

In [88]:
Match_title = []
Series = []
Place = []
Date = []
Time = []

In [93]:
for i in driver.find_elements_by_xpath('//span[@class="u-unskewed-text fixture__format"]'):
    Match_title.append(i.text) ### appending match titles.
for i in driver.find_elements_by_xpath('//span[@class="u-unskewed-text fixture__tournament-label u-truncated"]'):
    Series.append(i.text) ### Appending Series name
for i in driver.find_elements_by_xpath('//p[@class="fixture__additional-info"]/span'):
    Place.append(i.text)  ### Appending Place
for i in driver.find_elements_by_xpath('//span[@class="fixture__time"]'):
    Time.append(i.text) ### appending Time
for i in driver.find_elements_by_xpath('//div[@class="fixture__datetime desktop-only"]'):
    Date.append(i.text.replace('\n',' ')) ### Appending
print(len(Match_title),len(Series),len(Place),len(Date),len(Time))

### Creating DataFrame
df = pd.DataFrame({})
df['Match title'] = Match_title
df['Series'] = Series
df['Place'] = Place
df['Date'] = Date
df['Time'] = Time
df  ### Printing df

14 14 14 14 14

,Match title,Series,Place,Date,Time
0,TEST,ENGLAND V INDIA 2021,"The Oval, London",Thursday 02 SEPTEMBER 15:30 IST,15:30 IST
1,TEST,ENGLAND V INDIA 2021,"Old Trafford, Manchester",Friday 10 SEPTEMBER 15:30 IST,15:30 IST
2,T20I,2021 ICC MEN'S T20 WORLD CUP,"Dubai International Cricket Stadium, Dubai",Sunday 24 OCTOBER 19:30 IST,19:30 IST
3,T20I,2021 ICC MEN'S T20 WORLD CUP,"Dubai International Cricket Stadium, Dubai",Sunday 31 OCTOBER 19:30 IST,19:30 IST
4,T20I,2021 ICC MEN'S T20 WORLD CUP,"Sheikh Zayed Cricket Stadium, Abu Dhabi",Wednesday 03 NOVEMBER 19:30 IST,19:30 IST
5,T20I,2021 ICC MEN'S T20 WORLD CUP,"Dubai International Cricket Stadium, Dubai",Friday 05 NOVEMBER 19:30 IST,19:30 IST
6,T20I,2021 ICC MEN'S T20 WORLD CUP,"Dubai International Cricket Stadium, Dubai",Monday 08 NOVEMBER 19:30 IST,19:30 IST
7,TEST,ENGLAND V INDIA 2021,"The Oval, London",Thursday 02 SEPTEMBER 15:30 IST,15:30 IST
8,TEST,ENGLAND V INDIA 2021,"Old Trafford, Manchester",Friday 10 SEPTEMBER 15:30 IST,15:30 IST
9,T20I,2021 ICC MEN'S T20 WORLD CUP,"Dubai International Cricket Stadium, Dubai",Sunday 24 OCTOBER 19:30 IST,19:30 IST
10,T20I,2021 ICC MEN'S T20 WORLD CUP,"Dubai International Cricket Stadium, Dubai",Sunday 31 OCTOBER 19:30 IST,19:30 IST
11,T20I,2021 ICC MEN'S T20 WORLD CUP,"Sheikh Zayed Cricket Stadium, Abu Dhabi",Wednesday 03 NOVEMBER 19:30 IST,19:30 IST
12,T20I,2021 ICC MEN'S T20 WORLD CUP,"Dubai International Cricket Stadium, Dubai",Friday 05 NOVEMBER 19:30 IST,19:30 IST
13,T20I,2021 ICC MEN'S T20 WORLD CUP,"Dubai International Cricket Stadium, Dubai",Monday 08 NOVEMBER 19:30 IST,19:30 IST

In [94]:
##____________________________________________End__________________________________________________________________________

In [115]:
driver.get('https://www.guru99.com/')

In [116]:
testing = driver.find_element_by_xpath('//span[@class="nav-drop-title-wrap"]')
testing.click()
time.sleep(1)
selenium = driver.find_element_by_id('menu-item-4622')
selenium.click()

In [120]:
Exception_handling =  driver.find_element_by_xpath('//a[@title="Selenium Exception Handling (Common Exceptions List)"]')
Exception_handling.click()

In [123]:
Exception_name = [] 
for i in driver.find_elements_by_xpath('//table[@class="table table-striped"]/tbody/tr/td[1]'):
    Exception_name.append(i.text)
Exception_name

['ElementNotVisibleException',
 'ElementNotSelectableException',
 'NoSuchElementException',
 'NoSuchFrameException',
 'NoAlertPresentException',
 'NoSuchWindowException',
 'StaleElementReferenceException',
 'SessionNotFoundException',
 'TimeoutException',
 'WebDriverException',
 'ConnectionClosedException',
 'ElementClickInterceptedException',
 'ElementNotInteractableException',
 'ErrorInResponseException',
 'ErrorHandler.UnknownServerException',
 'ImeActivationFailedException',
 'ImeNotAvailableException',
 'InsecureCertificateException',
 'InvalidArgumentException',
 'InvalidCookieDomainException',
 'InvalidCoordinatesException',
 'InvalidElementStateExceptio',
 'InvalidSessionIdException',
 'InvalidSwitchToTargetException',
 'JavascriptException',
 'JsonException',
 'NoSuchAttributeException',
 'MoveTargetOutOfBoundsException',
 'NoSuchContextException',
 'NoSuchCookieException',
 'NotFoundException',
 'RemoteDriverServerException',
 'ScreenshotException',
 'SessionNotCreatedException',
 'UnableToSetCookieException',
 'UnexpectedTagNameException',
 'UnhandledAlertException',
 'UnexpectedAlertPresentException',
 'UnknownMethodException',
 'UnreachableBrowserException',
 'UnsupportedCommandException']

In [124]:
Description = [] 
for i in driver.find_elements_by_xpath('//table[@class="table table-striped"]/tbody/tr/td[2]'):
    Description.append(i.text)
Description

['This type of Selenium exception occurs when an existing element in DOM has a feature set as hidden.',
 'This Selenium exception occurs when an element is presented in the DOM, but you can be able to select. Therefore, it is not possible to interact.',
 'This Exception occurs if an element could not be found.',
 'This Exception occurs if the frame target to be switched to does not exist.',
 'This Exception occurs when you switch to no presented alert.',
 'This Exception occurs if the window target to be switch does not exist.',
 'This Selenium exception occurs happens when the web element is detached from the current DOM.',
 'The WebDriver is acting after you quit the browser.',
 'Thrown when there is not enough time for a command to be completed. For Example, the element searched wasn’t found in the specified time.',
 'This Exception takes place when the WebDriver is acting right after you close the browser.',
 'This type of Exception takes place when there is a disconnection in the driver.',
 'The command may not be completed as the element receiving the events is concealing the element which was requested clicked.',
 'This Selenium exception is thrown when any element is presented in the DOM. However, it is impossible to interact with such an element.',
 'This happens while interacting with the Firefox extension or the remote driver server.',
 'Exception is used as a placeholder in case if the server returns an error without a stack trace.',
 'This expectation will occur when IME engine activation has failed.',
 'It takes place when IME support is unavailable.',
 'Navigation made the user agent to hit a certificate warning. This can cause by an invalid or expired TLS certificate.',
 'It occurs when an argument does not belong to the expected type.',
 'This happens when you try to add a cookie under a different domain instead of current URL.',
 'This type of Exception matches an interacting operation that is not valid.',
 'It occurs when command can’t be finished when the element is invalid.',
 'This Exception took place when the given session ID is not included in the list of active sessions. It means the session does not exist or is inactive either.',
 'This occurs when the frame or window target to be switched does not exist.',
 'This issue occurs while executing JavaScript given by the user.',
 'It occurs when you afford to get the session when the session is not created.',
 'This kind of Exception occurs when the attribute of an element could not be found.',
 'It takes place if the target provided to the ActionChains move() methodology is not valid. For Example, out of the document.',
 'ContextAware does mobile device testing.',
 'This Exception occurs when no cookie matching with the given pathname found for all the associated cookies of the currently browsing document.',
 'This Exception is a subclass of WebDriverException. This will occur when an element on the DOM does not exist.',
 'This Selenium exception is thrown when the server is not responding because of the problem that the capabilities described are not proper.',
 'It is not possible to capture a screen.',
 'It happens when a new session could not be successfully created.',
 'This occurs if a driver is unable to set a cookie.',
 'Happens if a support class did not get a web element as expected.',
 'This expectation occurs when there is an alert, but WebDriver is not able to perform Alert operation.',
 'It occurs when there is the appearance of an unexpected alert.',
 'This Exception happens when the requested command matches with a known URL but and not matching with a methodology for a specific URL.',
 'This Exception occurs only when the browser is not able to be opened or crashed because of some reason.',
 'This occurs when remote WebDriver does n’t send valid commands as expected.']

In [125]:
df = pd.DataFrame({})
df['Exception name'] = Exception_name
df['Description'] = Description
df

,Exception name,Description
0,ElementNotVisibleException,This type of Selenium exception occurs when an...
1,ElementNotSelectableException,This Selenium exception occurs when an element...
2,NoSuchElementException,This Exception occurs if an element could not ...
3,NoSuchFrameException,This Exception occurs if the frame target to b...
4,NoAlertPresentException,This Exception occurs when you switch to no pr...
5,NoSuchWindowException,This Exception occurs if the window target to ...
6,StaleElementReferenceException,This Selenium exception occurs happens when th...
7,SessionNotFoundException,The WebDriver is acting after you quit the bro...
8,TimeoutException,Thrown when there is not enough time for a com...
9,WebDriverException,This Exception takes place when the WebDriver ...
10,ConnectionClosedException,This type of Exception takes place when there ...
11,ElementClickInterceptedException,The command may not be completed as the elemen...
12,ElementNotInteractableException,This Selenium exception is thrown when any ele...
13,ErrorInResponseException,This happens while interacting with the Firefo...
14,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
15,ImeActivationFailedException,This expectation will occur when IME engine ac...
16,ImeNotAvailableException,It takes place when IME support is unavailable.
17,InsecureCertificateException,Navigation made the user agent to hit a certif...
18,InvalidArgumentException,It occurs when an argument does not belong to ...
19,InvalidCookieDomainException,This happens when you try to add a cookie unde...
20,InvalidCoordinatesException,This type of Exception matches an interacting ...
21,InvalidElementStateExceptio,It occurs when command can’t be finished when ...
22,InvalidSessionIdException,This Exception took place when the given sessi...
23,InvalidSwitchToTargetException,This occurs when the frame or window target to...
24,JavascriptException,This issue occurs while executing JavaScript g...
25,JsonException,It occurs when you afford to get the session w...
26,NoSuchAttributeException,This kind of Exception occurs when the attribu...
27,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
28,NoSuchContextException,ContextAware does mobile device testing.
29,NoSuchCookieException,This Exception occurs when no cookie matching ...
30,NotFoundException,This Exception is a subclass of WebDriverExcep...
31,RemoteDriverServerException,This Selenium exception is thrown when the ser...
32,ScreenshotException,It is not possible to capture a screen.
33,SessionNotCreatedException,It happens when a new session could not be suc...
34,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
35,UnexpectedTagNameException,Happens if a support class did not get a web e...
36,UnhandledAlertException,This expectation occurs when there is an alert...
37,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
38,UnknownMethodException,This Exception happens when the requested comm...
39,UnreachableBrowserException,This Exception occurs only when the browser is...
40,UnsupportedCommandException,This occurs when remote WebDriver does n’t sen...

In [126]:
##________________________________________________End_________________________________________________

In [29]:
driver.get('http://statisticstimes.com/')
time.sleep(5)
economy = driver.find_element_by_xpath('//div[@class="navbar"]/div[2]')
india = driver.find_element_by_xpath('//div[@class="navbar"]/div[2]/div/a[3]')
action = ActionChains(driver)
action.move_to_element(economy).click(india).perform()
time.sleep(2)

try:
    dismiss_ad = driver.find_element_by_xpath('//div[@id="dismiss-button"]')
    dismiss_ad.click()
except NoSuchElementException:
    print('No ad pop-up')

GDP = []
for i in driver.find_elements_by_xpath('//div[@style="float:left;background-color:#E6E6B8;width:400px;height:800px;"]/ul/li'):
    GDP.append(i.text)

No ad pop-up

In [30]:
GDP = []
GDP_url = []
for i in driver.find_elements_by_xpath('//div[@style="float:left;background-color:#E6E6B8;width:400px;height:800px;"]/ul/li/a'):
    GDP.append(i.text)
    GDP_url.append(i.get_attribute('href'))
GDP_url

['http://statisticstimes.com/economy/country/india-quarterly-gdp-growth.php',
 'http://statisticstimes.com/economy/country/india-gdp.php',
 'http://statisticstimes.com/economy/country/india-gdp-per-capita.php',
 'http://statisticstimes.com/economy/country/india-gdp-growth.php',
 'http://statisticstimes.com/economy/country/india-gdp-sectorwise.php',
 'http://statisticstimes.com/economy/country/india-gdp-growth-sectorwise.php',
 'http://statisticstimes.com/economy/agriculture-sector-in-india.php',
 'http://statisticstimes.com/economy/industry-sector-in-india.php',
 'http://statisticstimes.com/economy/manufacturing-sector-in-india.php',
 'http://statisticstimes.com/economy/mining-sector-in-india.php',
 'http://statisticstimes.com/economy/services-sector-in-india.php',
 'http://statisticstimes.com/economy/indian-rupee-historical-exchange-rate.php',
 'http://statisticstimes.com/economy/indian-rupee-performance-yearwise.php']

In [44]:
Source = []
Date = []
About = []
for i in GDP_url:
    driver.get(i)
    time.sleep(5)
    try:
        source = driver.find_element_by_xpath('//table[@class="reference"]/tbody/tr/td[2]')
        Source.append(source.text)
    except NoSuchElementException:
        Source.append('-')
    try:
        date = driver.find_element_by_xpath('//table[@class="reference"]/tbody/tr[2]/td[2]')
        Date.append(date.text)
    except:
        try:
            date = driver.find_element_by_xpath('//table[@class="reference"]/tbody/tr[3]/td[2]')
            Date.append(date.text)
        except:
            try:
                date = driver.find_element_by_xpath('//table[@class="reference"]/tbody/tr[4]/td[2]')
                Date.append(date.text)
            except NoSuchElementException:
                Date.append('-')
    try:
        about = driver.find_elements_by_xpath('//div[@class="para"]/p[1]')
        for i in about:
            About.append(i.text)
    except NoSuchElementException:
        About.append("-")
print(len(Source),len(Date),len(About))

KeyboardInterrupt:

In [43]:
About

['GDP at constant (2011-12) prices in Q1 of 2021-22 is estimated at 32.38 lakh crore INR, showing a best-ever quarterly GDP growth rate of 20.13 percent over the corresponding quarter of the previous year. GDP growth rate was -24.43% in the year-earlier quarter and 1.64% in the preceding one. GDP growth rate Q1 of FY22 is -9.22% over the Q1 of FY20 when the growth rate was lowest ever.',
 'Real GDP or Gross Domestic Product (GDP) at constant (2011-12) prices in the year 2020-21 is estimated at ₹ 135.13 lakh crore, as against the First Revised Estimate of GDP for 2019-20 of ₹ 145.69 lakh crore. The growth in GDP during 2019-20 is estimated at -7.3 percent. Nominal GDP or GDP at current prices in the year 2020-21 is estimated to attain a level of ₹ 197.46 lakh crore against the First Revised Estimates of ₹ 203.51 lakh crore in 2019-20, showing a change of -3.0 percent.',
 'Nominal GDP per capita or GDP per capita at current prices in 2020-21 is estimated at ₹ 145,679 against ₹ 151,760 for 2019-20. At constant (2011-12) prices, GDP per capita is 99,694 INR for 2020-21.',
 "According to the IMF World Economic Outlook (April-2021), India's GDP growth rate in 2021 is projected at 12.55%. India is in 5th position out of 193 economies. India is among six economies that will experience a double-digit growth rate in 2021. With a 7.965% contraction in 2020, India is at the 150th position.",
 "The services sector is the largest sector of India. Gross Value Added (GVA) at current prices for the services sector is estimated at 96.54 lakh crore INR in 2020-21. The services sector accounts for 53.89% of total India's GVA of 179.15 lakh crore Indian rupees. With GVA of Rs. 46.44 lakh crore, the Industry sector contributes 25.92%. While Agriculture and allied sector share 20.19%.",
 'At 2011-12 prices, GVA growth rates of Agriculture, Industry, and Services sector are 3.63%, -6.96%, and -8.36%, respectively in the year 2020-21. At current prices, growth rates are Agriculture (6.56%), Industry (-5.61%), and Services (-4.86%).']

In [ ]:
###______________________________________________________End______________________________________________________________

In [54]:
driver.get('https://github.com/')
time.sleep(3)

In [57]:
explore = driver.find_element_by_xpath('/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/summary')
trending = driver.find_element_by_xpath('//a[@data-ga-click="(Logged out) Header, go to Trending"]').get_attribute('href')

action = ActionChains(driver)
action.move_to_element(explore).perform(driver.get(trending))

TypeError: perform() takes 1 positional argument but 2 were given

In [82]:
rep_title = []
for i in driver.find_elements_by_xpath('//span[@class="text-normal"]'):
    rep_title.append(i.text.replace('/',''))

rep_descrp = []
for i in driver.find_elements_by_xpath('//p[@class="col-9 color-text-secondary my-1 pr-4"]'):
    rep_descrp.append(i.text)
    
Lang = []
lang = driver.find_elements_by_xpath('//div[@class="f6 color-text-secondary mt-2"]')
for i in lang:
    try:
        temp = driver.find_element_by_xpath('//div[@class="f6 color-text-secondary mt-2"]/span/span[2]')
        Lang.append(i.text.replace('\n*',''))
    except NoSuchElementException:
        Lang.append('-')

Contributor_count = []
for i in driver.find_elements_by_xpath('//div[@class="f6 color-text-secondary mt-2"]/a[2]'):
    Contributor_count.append(i.text)
print(len(rep_title),len(rep_descrp),len(Lang),len(Contributor_count))

#creating dataframe
df = pd.DataFrame({})
df['Repository title'] = rep_title
df['Repository description'] = rep_descrp
df['Contributors count'] = Contributor_count
df['Language used'] = Lang
df

25 25 25 25

,Repository title,Repository description,Contributors count,Language used
0,GTAmodding,"GTA III, Vice City",798,"C++ 6,432 798 Built by\n207 stars today"
1,VickScarlet,やり直すんだ。そして、次はうまくやる。,"1,144","JavaScript 5,317 1,144 Built by\n1,162 stars t..."
2,lootproject,Loot Project website,78,TypeScript 182 78 Built by\n27 stars today
3,TheAlgorithms,All Algorithms implemented in Python,"31,420","Python 116,532 31,420 Built by\n333 stars today"
4,Anish-Agnihotri,Scripts to collect statistics about LOOT + der...,49,JavaScript 155 49 Built by\n38 stars today
5,TheAlgorithms,Collection of various algorithms in mathematic...,"4,067","C++ 15,243 4,067 Built by\n179 stars today"
6,donnemartin,Learn how to design large-scale systems. Prep ...,"26,377","Python 143,252 26,377 Built by\n256 stars today"
7,microsoft,Windows system utilities to maximize productivity,"3,282","C# 59,772 3,282 Built by\n249 stars today"
8,openwrt,This repository is a mirror of https://git.ope...,"6,168","C 9,392 6,168 Built by\n23 stars today"
9,v2fly,A platform for building proxies to bypass netw...,"1,890","Go 11,405 1,890 Built by\n152 stars today"
10,MarlinFirmware,Marlin is an optimized firmware for RepRap 3D ...,"14,931","C++ 11,726 14,931 Built by\n19 stars today"
11,HashLips,Create generative art by using the canvas api ...,108,JavaScript 390 108 Built by\n117 stars today
12,vxunderground,Collection of malware source code for a variet...,705,"Assembly 7,055 705 Built by\n359 stars today"
13,metaplex-foundation,Protocol and application framework for decentr...,"1,255","Rust 830 1,255 Built by\n87 stars today"
14,armosec,kubescape is the first tool for testing if Kub...,105,"Go 3,228 105 Built by\n216 stars today"
15,wrfree,freefq账号已恢复！翻墙、免费翻墙、免费科学上网、免费节点、免费梯子、免费ss/v2ra...,33,187 33 Built by\n49 stars today
16,bespoyasov,React + TypeScript app built using clean archi...,34,TypeScript 400 34 Built by\n219 stars today
17,TheAlgorithms,A repository for All algorithms implemented in...,"2,347","JavaScript 13,476 2,347 Built by\n282 stars today"
18,0voice,【未来服务器端编程语言】最全空降golang资料补给包（满血战斗），包含文章，书籍，作者论文...,430,"1,998 430 Built by\n103 stars today"
19,iptv-org,Collection of publicly available IPTV channels...,"3,194","JavaScript 38,932 3,194 Built by\n78 stars today"
20,Anuken,A sandbox tower defense game,"1,665","Java 11,534 1,665 Built by\n59 stars today"
21,30-seconds,Short JavaScript code snippets for all your de...,"8,910","JavaScript 82,730 8,910 Built by\n214 stars today"
22,NotLuksus,A tool to generate generative NFT art projects.,63,JavaScript 198 63 Built by\n32 stars today
23,vnpy,基于Python的开源量化交易平台开发框架,"6,580","C++ 15,948 6,580 Built by\n71 stars today"
24,jackfrued,Python - 100天从新手到大师,"42,635","Python 107,833 42,635 Built by\n70 stars today"

In [83]:
##__________________________________________________End_____________________________________________

In [35]:
driver.get('https://www.billboard.com/')

In [52]:
charts = driver.find_element_by_xpath('//a[@href="/charts"]')
hot_100 = driver.find_element_by_xpath('//a[@href="/charts/hot-100"]').get_attribute('href')
action = ActionChains(driver)
action.move_to_element(charts).perform(driver.get(hot_100))

TypeError: perform() takes 1 positional argument but 2 were given

In [59]:
Song_name = []
for i in driver.find_elements_by_xpath('//span[@class="chart-element__information"]/span[1]'):
    Song_name.append(i.text)

Artist_name = []
for i in driver.find_elements_by_xpath('//span[@class="chart-element__information"]/span[2]'):
    Artist_name.append(i.text)

LW_rank = []
for i in driver.find_elements_by_xpath('//div[@class="chart-element__meta text--center color--secondary text--last"]'):
    LW_rank.append(i.text)

WKs_on_board = []
for i in driver.find_elements_by_xpath('//div[@class="chart-element__meta text--center color--secondary text--week"]'):
    WKs_on_board.append(i.text)

P_rank = []
for i in driver.find_elements_by_xpath('//div[@class="chart-element__meta text--center color--secondary text--peak"]'):
    P_rank.append(i.text)
print(len(Song_name),len(Artist_name),len(LW_rank),len(P_rank),len(WKs_on_board))

100 100 100 100 100

In [60]:
## Creating dataFrame
df = pd.DataFrame({})
df['Song name'] = Song_name
df['Artist name'] = Artist_name
df['Last week rank'] = LW_rank
df['Peak rank'] = P_rank
df['Weeks on Board'] = WKs_on_board
df

,Song name,Artist name,Last week rank,Peak rank,Weeks on Board
0,Stay,The Kid LAROI & Justin Bieber,1,1,7
1,Bad Habits,Ed Sheeran,2,2,9
2,Good 4 U,Olivia Rodrigo,3,1,15
3,Kiss Me More,Doja Cat Featuring SZA,5,3,20
4,Industry Baby,Lil Nas X & Jack Harlow,7,2,5
...,...,...,...,...,...
95,Tick Tock,Young Thug,-,96,1
96,Permission To Dance,BTS,66,1,7
97,AM,Nio Garcia X J Balvin X Bad Bunny,85,41,9
98,Time Heals,Rod Wave,-,99,1
99,Thinking 'Bout You,Dustin Lynch Featuring Lauren Alaina Or MacKen...,91,91,2

In [61]:
##____________________________________________________End_______________________________________________________________

In [98]:
driver.get('https://www.naukri.com/')
time.sleep(10)
try:
    later = driver.find_element_by_xpath('//span[@class="fr geoLocBtn later"]')
    later.click()
except NoSuchElementException:
    print('Element not found')

Element not found

In [99]:
recruiters = driver.find_element_by_xpath('//a[@title="Search Recruiters"]').get_attribute('href')
driver.get(recruiters)
time.sleep(3)
search = driver.find_element_by_xpath('//input[@class="sugInp"]')
search.clear()
search.send_keys('Data science')
time.sleep(1)
button = driver.find_element_by_id('qsbFormBtn')
button.click()

In [100]:
Name = []
for i in driver.find_elements_by_xpath('//span[@class="fl ellipsis"]'):
    Name.append(i.text)

Designation = []
for i in driver.find_elements_by_xpath('//span[@class="ellipsis clr"]'):
    Designation.append(i.text)



Skills = []
for i in driver.find_elements_by_xpath('//div[@class="hireSec highlightable"]'):
    Skills.append(i.text)

print(len(Name),len(Designation),len(Skills))

50 50 50

In [101]:
urls = [] 
for i in driver.find_elements_by_xpath('//p[@class="highlightable"]/a[1]'):
    urls.append(i.get_attribute('href'))
len(urls)

50

In [103]:
Company = []
Location = []
for i in urls:
    driver.get(i)
    time.sleep(3)
    try:
        temp = driver.find_elements_by_xpath('//a[@class="fl ellipsis widLrg"]')
        for i in temp[:1]:
            Company.append(i.text)
        for i in temp[1:]:
            Location.append(i.text)
    except:
        Company.append('-')
        Location.append('-')

In [107]:
print(len(Company),len(Location))

50 50

In [106]:
df = pd.DataFrame({})
df['Name'] = Name
df['Designation'] = Designation
df['Company'] = Company
df['Skills they hire for'] = Skills
df['Location'] = Location
df

,Name,Designation,Company,Skills they hire for,Location
0,Aakash Harit,HR Manager,Data Science Network,"Classic ASP Developer, Internet Marketing Prof...",Delhi
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,".Net, Java, Data Science, Linux Administration...",Hyderabad / Secunderabad
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,"Data Science, Artificial Intelligence, Machine...",Pune
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,"Mean Stack, javascript, angularjs, mongodb, We...",Ahmedabad
4,subhas patel,Founder CEO,LibraryXProject,"Hadoop, Spark, Digital Strategy, Data Architec...",UK - (london)
5,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,"Analytics, Business Intelligence, Business Ana...",Vadodara / Baroda
6,Institute for Financial Management and Resear,Programme Manager,IFMR,Data Science,Chennai
7,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,"Machine Learning, algorithms, Go Getter, Compu...",Trivandrum
8,Asif Lucknowi,Director,Weupskill- Live Wire India,"Technical Training, Software Development, Pres...",Indore
9,InstaFinancials,Human Resource,CBL Data Science Private Limited,"Software Development, It Sales, Account Manage...",Bengaluru / Bangalore
10,Priyanka Akiri,HR Manager,Infinitive Software Solutions Pvt.Ltd.,"Oracle Dba, Data Science, Data Warehousing, ET...",Hyderabad
11,Kalpana Dumpala,Executive Hiring,Innominds Software,"Qa, Ui/ux, Java Developer, Java Architect, C++...",Hyderabad / Secunderabad
12,Mubarak,Company HR,MoneyTap,"Business Intelligence, Data Warehousing, Data ...",Bengaluru / Bangalore
13,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,"Office Administration, Hr Administration, tele...",Mumbai
14,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,"Qlikview, Qlik Sense, Microsoft Azure, Power B...",Pune
15,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,"Social Media, digital media maketing, seo, smm...",Hyderabad / Secunderabad
16,Kapil Devang,HR Manager,BISP Solutions,"Big Data, Hadoop, Data Analytics, Data Science",Bhopal
17,Manisha Yadav,HR Executive,Easi Tax,"Telecalling, Client Interaction, Marketing, Re...",Navi Mumbai
18,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Data Science,Cochin
19,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE LIMITED,"Corporate Sales, Software Development, Softwar...",Delhi
20,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,"Data Analytics, Data Science, Machine Learning...",Hyderabad / Secunderabad
21,Rithika dadwal,HR Recruiter,Affine Analytics,"Data Science, Machine Learning, Python, R, Dee...",Pune
22,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,"Big Data, Data Science, Artificial Intelligenc...",Pune
23,Shaun Rao,Manager Human Resources,Exela Technologies,"Java, Net, Angularjs, Hr, Infrastructure, Mana...",Pune
24,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,"Data Science, Artificial Intelligence, Machine...",Pune
25,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private Limited,"Software Architecture, Vp Engineering, Product...",Bengaluru / Bangalore
26,kumar,Proprietor,trainin,"Data Science, Hadoop, Rpas, Devops, Python, Aw...",Bengaluru / Bangalore
27,Sunil Vedula,CEO,Nanoprecise Sci Corp,"Signal Processing, Machine Learning, Neural Ne...",Others
28,Rajat Kumar,Founder CEO,R.S Consultancy & Services,"Web Technologies, Project Management, Software...",Delhi
29,Priya Khare,Senior Manager,Independent Consultant,"Data Science, Artificial Intelligence, analyti...",Bengaluru / Bangalore
30,Dhruv Dev Dubey,Company Recruitment Head,Confidential,"Server Administartion, Verilog, Vhdl, Digital ...",Bengaluru / Bangalore
31,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd","Data Analytics, Managed Services, Team Leading...",Mysoru / Mysore
32,SREEDHAR,Recruitment Consultant,JOBSMILL BUSINESS SOLUTIONS PRIVATE LIMITED,"Data Science, Machine Learning, Big Data Analy...",Hyderabad / Secunderabad
33,Radha Manivasagam,HR Executive,Techcovery,"Python, Artificial Intelligence, Machine Learn...",Bengaluru / Bangalore
34,Prateek Kumar,Head,Trisect,"Java, Python, Angularjs, Software Testing, Mac...",Noida
35,Amit Sharma,Consultant,ASCO consulting,"Machine Learning, Artificial Intelligence, Dat...",New Delhi
36,Kanan,senior technology instructor,NY INST,"C, C++, Artificial Intelligence, Python, Php, ...",Chennai
37,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research & Consulting Co. India,"Relationship Management, Retail Sales, Private...",Aligarh
38,Brad,"Manager, Technical Recruiting",O.C. Tanner,"Data Science, Software Engineering",Salt Lake City
39,Rutuja Pawar,Technical Recruiter,Demand Matrix,"Data Science, Big Data Analytics, Digital Mark...",Pune
40,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,"Data Science, Recruitment, Salary",Bengaluru / Bangalore
41,Ankit Sinha,Head Analytics,Suntech Global,"B.Tech, Tableau, Statistics, R, Analytics, Tim...",Mumbai
42,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,"Software Development, Business Intelligence, B...",Indore
43,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,"Data Science, Node.js, Angularjs",Bengaluru / Bangalore
44,Ashwini,Director Global Delivery,MRP Advisers,"Data Science, Media Marketing, Resource Planni...",MYSORE
45,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,"Data Analysis, Learning, Data Science, Compute...",Hyderabad / Secunderabad
46,Rajani Nagaraj,HR Manager,WildJasmine,"Java, Hadoop, R, Machine Learning, Spark, Flum...",Bengaluru / Bangalore
47,ROHIT Kumar,Architect,LNT Private Limited,"Software Development, Core Java, Unit Testing,...",Mumbai
48,Amir Chowdhury,Managing Partner,Granular.ai,"Machine Learning, Data Science, Product Manage...",
49,Shailja Mishra,HR Manager,Certybox Pvt.Ltd.,"consulting, Education Counseling, Educational ...",Noida

In [108]:
##_________________________________________________End_________________________________________________________________

In [109]:
driver.get('https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare')

In [111]:
Name = []
for i in driver.find_elements_by_xpath('//table[@class="in-article sortable"]/tbody/tr/td[2]'):
    Name.append(i.text)
Name

['Da Vinci Code,The',
 'Harry Potter and the Deathly Hallows',
 "Harry Potter and the Philosopher's Stone",
 'Harry Potter and the Order of the Phoenix',
 'Fifty Shades of Grey',
 'Harry Potter and the Goblet of Fire',
 'Harry Potter and the Chamber of Secrets',
 'Harry Potter and the Prisoner of Azkaban',
 'Angels and Demons',
 "Harry Potter and the Half-blood Prince:Children's Edition",
 'Fifty Shades Darker',
 'Twilight',
 'Girl with the Dragon Tattoo,The:Millennium Trilogy',
 'Fifty Shades Freed',
 'Lost Symbol,The',
 'New Moon',
 'Deception Point',
 'Eclipse',
 'Lovely Bones,The',
 'Curious Incident of the Dog in the Night-time,The',
 'Digital Fortress',
 'Short History of Nearly Everything,A',
 'Girl Who Played with Fire,The:Millennium Trilogy',
 'Breaking Dawn',
 'Very Hungry Caterpillar,The:The Very Hungry Caterpillar',
 'Gruffalo,The',
 "Jamie's 30-Minute Meals",
 'Kite Runner,The',
 'One Day',
 'Thousand Splendid Suns,A',
 "Girl Who Kicked the Hornets' Nest,The:Millennium Trilogy",
 "Time Traveler's Wife,The",
 'Atonement',
 "Bridget Jones's Diary:A Novel",
 'World According to Clarkson,The',
 "Captain Corelli's Mandolin",
 'Sound of Laughter,The',
 'Life of Pi',
 'Billy Connolly',
 'Child Called It,A',
 "Gruffalo's Child,The",
 "Angela's Ashes:A Memoir of a Childhood",
 'Birdsong',
 'Northern Lights:His Dark Materials S.',
 'Labyrinth',
 'Harry Potter and the Half-blood Prince',
 'Help,The',
 'Man and Boy',
 'Memoirs of a Geisha',
 "No.1 Ladies' Detective Agency,The:No.1 Ladies' Detective Agency S.",
 'Island,The',
 'PS, I Love You',
 'You are What You Eat:The Plan That Will Change Your Life',
 'Shadow of the Wind,The',
 'Tales of Beedle the Bard,The',
 'Broker,The',
 "Dr. Atkins' New Diet Revolution:The No-hunger, Luxurious Weight Loss P",
 'Subtle Knife,The:His Dark Materials S.',
 'Eats, Shoots and Leaves:The Zero Tolerance Approach to Punctuation',
 "Delia's How to Cook:(Bk.1)",
 'Chocolat',
 'Boy in the Striped Pyjamas,The',
 "My Sister's Keeper",
 'Amber Spyglass,The:His Dark Materials S.',
 'To Kill a Mockingbird',
 'Men are from Mars, Women are from Venus:A Practical Guide for Improvin',
 'Dear Fatty',
 'Short History of Tractors in Ukrainian,A',
 'Hannibal',
 'Lord of the Rings,The',
 'Stupid White Men:...and Other Sorry Excuses for the State of the Natio',
 'Interpretation of Murder,The',
 'Sharon Osbourne Extreme:My Autobiography',
 'Alchemist,The:A Fable About Following Your Dream',
 "At My Mother's Knee ...:and Other Low Joints",
 'Notes from a Small Island',
 'Return of the Naked Chef,The',
 'Bridget Jones: The Edge of Reason',
 "Jamie's Italy",
 'I Can Make You Thin',
 'Down Under',
 'Summons,The',
 'Small Island',
 'Nigella Express',
 'Brick Lane',
 "Memory Keeper's Daughter,The",
 'Room on the Broom',
 'About a Boy',
 'My Booky Wook',
 'God Delusion,The',
 '"Beano" Annual,The',
 'White Teeth',
 'House at Riverton,The',
 'Book Thief,The',
 'Nights of Rain and Stars',
 'Ghost,The',
 'Happy Days with the Naked Chef',
 'Hunger Games,The:Hunger Games Trilogy',
 "Lost Boy,The:A Foster Child's Search for the Love of a Family",
 "Jamie's Ministry of Food:Anyone Can Learn to Cook in 24 Hours"]

In [112]:
Author = []
for i in driver.find_elements_by_xpath('//table[@class="in-article sortable"]/tbody/tr/td[3]'):
    Author.append(i.text)
Author

['Brown, Dan',
 'Rowling, J.K.',
 'Rowling, J.K.',
 'Rowling, J.K.',
 'James, E. L.',
 'Rowling, J.K.',
 'Rowling, J.K.',
 'Rowling, J.K.',
 'Brown, Dan',
 'Rowling, J.K.',
 'James, E. L.',
 'Meyer, Stephenie',
 'Larsson, Stieg',
 'James, E. L.',
 'Brown, Dan',
 'Meyer, Stephenie',
 'Brown, Dan',
 'Meyer, Stephenie',
 'Sebold, Alice',
 'Haddon, Mark',
 'Brown, Dan',
 'Bryson, Bill',
 'Larsson, Stieg',
 'Meyer, Stephenie',
 'Carle, Eric',
 'Donaldson, Julia',
 'Oliver, Jamie',
 'Hosseini, Khaled',
 'Nicholls, David',
 'Hosseini, Khaled',
 'Larsson, Stieg',
 'Niffenegger, Audrey',
 'McEwan, Ian',
 'Fielding, Helen',
 'Clarkson, Jeremy',
 'Bernieres, Louis de',
 'Kay, Peter',
 'Martel, Yann',
 'Stephenson, Pamela',
 'Pelzer, Dave',
 'Donaldson, Julia',
 'McCourt, Frank',
 'Faulks, Sebastian',
 'Pullman, Philip',
 'Mosse, Kate',
 'Rowling, J.K.',
 'Stockett, Kathryn',
 'Parsons, Tony',
 'Golden, Arthur',
 'McCall Smith, Alexander',
 'Hislop, Victoria',
 'Ahern, Cecelia',
 'McKeith, Gillian',
 'Zafon, Carlos Ruiz',
 'Rowling, J.K.',
 'Grisham, John',
 'Atkins, Robert C.',
 'Pullman, Philip',
 'Truss, Lynne',
 'Smith, Delia',
 'Harris, Joanne',
 'Boyne, John',
 'Picoult, Jodi',
 'Pullman, Philip',
 'Lee, Harper',
 'Gray, John',
 'French, Dawn',
 'Lewycka, Marina',
 'Harris, Thomas',
 'Tolkien, J. R. R.',
 'Moore, Michael',
 'Rubenfeld, Jed',
 'Osbourne, Sharon',
 'Coelho, Paulo',
 "O'Grady, Paul",
 'Bryson, Bill',
 'Oliver, Jamie',
 'Fielding, Helen',
 'Oliver, Jamie',
 'McKenna, Paul',
 'Bryson, Bill',
 'Grisham, John',
 'Levy, Andrea',
 'Lawson, Nigella',
 'Ali, Monica',
 'Edwards, Kim',
 'Donaldson, Julia',
 'Hornby, Nick',
 'Brand, Russell',
 'Dawkins, Richard',
 '0',
 'Smith, Zadie',
 'Morton, Kate',
 'Zusak, Markus',
 'Binchy, Maeve',
 'Harris, Robert',
 'Oliver, Jamie',
 'Collins, Suzanne',
 'Pelzer, Dave',
 'Oliver, Jamie']

In [113]:
Volume = []
for i in driver.find_elements_by_xpath('//table[@class="in-article sortable"]/tbody/tr/td[2]'):
    Volume.append(i.text)
Volume

['Da Vinci Code,The',
 'Harry Potter and the Deathly Hallows',
 "Harry Potter and the Philosopher's Stone",
 'Harry Potter and the Order of the Phoenix',
 'Fifty Shades of Grey',
 'Harry Potter and the Goblet of Fire',
 'Harry Potter and the Chamber of Secrets',
 'Harry Potter and the Prisoner of Azkaban',
 'Angels and Demons',
 "Harry Potter and the Half-blood Prince:Children's Edition",
 'Fifty Shades Darker',
 'Twilight',
 'Girl with the Dragon Tattoo,The:Millennium Trilogy',
 'Fifty Shades Freed',
 'Lost Symbol,The',
 'New Moon',
 'Deception Point',
 'Eclipse',
 'Lovely Bones,The',
 'Curious Incident of the Dog in the Night-time,The',
 'Digital Fortress',
 'Short History of Nearly Everything,A',
 'Girl Who Played with Fire,The:Millennium Trilogy',
 'Breaking Dawn',
 'Very Hungry Caterpillar,The:The Very Hungry Caterpillar',
 'Gruffalo,The',
 "Jamie's 30-Minute Meals",
 'Kite Runner,The',
 'One Day',
 'Thousand Splendid Suns,A',
 "Girl Who Kicked the Hornets' Nest,The:Millennium Trilogy",
 "Time Traveler's Wife,The",
 'Atonement',
 "Bridget Jones's Diary:A Novel",
 'World According to Clarkson,The',
 "Captain Corelli's Mandolin",
 'Sound of Laughter,The',
 'Life of Pi',
 'Billy Connolly',
 'Child Called It,A',
 "Gruffalo's Child,The",
 "Angela's Ashes:A Memoir of a Childhood",
 'Birdsong',
 'Northern Lights:His Dark Materials S.',
 'Labyrinth',
 'Harry Potter and the Half-blood Prince',
 'Help,The',
 'Man and Boy',
 'Memoirs of a Geisha',
 "No.1 Ladies' Detective Agency,The:No.1 Ladies' Detective Agency S.",
 'Island,The',
 'PS, I Love You',
 'You are What You Eat:The Plan That Will Change Your Life',
 'Shadow of the Wind,The',
 'Tales of Beedle the Bard,The',
 'Broker,The',
 "Dr. Atkins' New Diet Revolution:The No-hunger, Luxurious Weight Loss P",
 'Subtle Knife,The:His Dark Materials S.',
 'Eats, Shoots and Leaves:The Zero Tolerance Approach to Punctuation',
 "Delia's How to Cook:(Bk.1)",
 'Chocolat',
 'Boy in the Striped Pyjamas,The',
 "My Sister's Keeper",
 'Amber Spyglass,The:His Dark Materials S.',
 'To Kill a Mockingbird',
 'Men are from Mars, Women are from Venus:A Practical Guide for Improvin',
 'Dear Fatty',
 'Short History of Tractors in Ukrainian,A',
 'Hannibal',
 'Lord of the Rings,The',
 'Stupid White Men:...and Other Sorry Excuses for the State of the Natio',
 'Interpretation of Murder,The',
 'Sharon Osbourne Extreme:My Autobiography',
 'Alchemist,The:A Fable About Following Your Dream',
 "At My Mother's Knee ...:and Other Low Joints",
 'Notes from a Small Island',
 'Return of the Naked Chef,The',
 'Bridget Jones: The Edge of Reason',
 "Jamie's Italy",
 'I Can Make You Thin',
 'Down Under',
 'Summons,The',
 'Small Island',
 'Nigella Express',
 'Brick Lane',
 "Memory Keeper's Daughter,The",
 'Room on the Broom',
 'About a Boy',
 'My Booky Wook',
 'God Delusion,The',
 '"Beano" Annual,The',
 'White Teeth',
 'House at Riverton,The',
 'Book Thief,The',
 'Nights of Rain and Stars',
 'Ghost,The',
 'Happy Days with the Naked Chef',
 'Hunger Games,The:Hunger Games Trilogy',
 "Lost Boy,The:A Foster Child's Search for the Love of a Family",
 "Jamie's Ministry of Food:Anyone Can Learn to Cook in 24 Hours"]

In [114]:
Publisher = []
for i in driver.find_elements_by_xpath('//table[@class="in-article sortable"]/tbody/tr/td[2]'):
    Publisher.append(i.text)
Publisher

['Da Vinci Code,The',
 'Harry Potter and the Deathly Hallows',
 "Harry Potter and the Philosopher's Stone",
 'Harry Potter and the Order of the Phoenix',
 'Fifty Shades of Grey',
 'Harry Potter and the Goblet of Fire',
 'Harry Potter and the Chamber of Secrets',
 'Harry Potter and the Prisoner of Azkaban',
 'Angels and Demons',
 "Harry Potter and the Half-blood Prince:Children's Edition",
 'Fifty Shades Darker',
 'Twilight',
 'Girl with the Dragon Tattoo,The:Millennium Trilogy',
 'Fifty Shades Freed',
 'Lost Symbol,The',
 'New Moon',
 'Deception Point',
 'Eclipse',
 'Lovely Bones,The',
 'Curious Incident of the Dog in the Night-time,The',
 'Digital Fortress',
 'Short History of Nearly Everything,A',
 'Girl Who Played with Fire,The:Millennium Trilogy',
 'Breaking Dawn',
 'Very Hungry Caterpillar,The:The Very Hungry Caterpillar',
 'Gruffalo,The',
 "Jamie's 30-Minute Meals",
 'Kite Runner,The',
 'One Day',
 'Thousand Splendid Suns,A',
 "Girl Who Kicked the Hornets' Nest,The:Millennium Trilogy",
 "Time Traveler's Wife,The",
 'Atonement',
 "Bridget Jones's Diary:A Novel",
 'World According to Clarkson,The',
 "Captain Corelli's Mandolin",
 'Sound of Laughter,The',
 'Life of Pi',
 'Billy Connolly',
 'Child Called It,A',
 "Gruffalo's Child,The",
 "Angela's Ashes:A Memoir of a Childhood",
 'Birdsong',
 'Northern Lights:His Dark Materials S.',
 'Labyrinth',
 'Harry Potter and the Half-blood Prince',
 'Help,The',
 'Man and Boy',
 'Memoirs of a Geisha',
 "No.1 Ladies' Detective Agency,The:No.1 Ladies' Detective Agency S.",
 'Island,The',
 'PS, I Love You',
 'You are What You Eat:The Plan That Will Change Your Life',
 'Shadow of the Wind,The',
 'Tales of Beedle the Bard,The',
 'Broker,The',
 "Dr. Atkins' New Diet Revolution:The No-hunger, Luxurious Weight Loss P",
 'Subtle Knife,The:His Dark Materials S.',
 'Eats, Shoots and Leaves:The Zero Tolerance Approach to Punctuation',
 "Delia's How to Cook:(Bk.1)",
 'Chocolat',
 'Boy in the Striped Pyjamas,The',
 "My Sister's Keeper",
 'Amber Spyglass,The:His Dark Materials S.',
 'To Kill a Mockingbird',
 'Men are from Mars, Women are from Venus:A Practical Guide for Improvin',
 'Dear Fatty',
 'Short History of Tractors in Ukrainian,A',
 'Hannibal',
 'Lord of the Rings,The',
 'Stupid White Men:...and Other Sorry Excuses for the State of the Natio',
 'Interpretation of Murder,The',
 'Sharon Osbourne Extreme:My Autobiography',
 'Alchemist,The:A Fable About Following Your Dream',
 "At My Mother's Knee ...:and Other Low Joints",
 'Notes from a Small Island',
 'Return of the Naked Chef,The',
 'Bridget Jones: The Edge of Reason',
 "Jamie's Italy",
 'I Can Make You Thin',
 'Down Under',
 'Summons,The',
 'Small Island',
 'Nigella Express',
 'Brick Lane',
 "Memory Keeper's Daughter,The",
 'Room on the Broom',
 'About a Boy',
 'My Booky Wook',
 'God Delusion,The',
 '"Beano" Annual,The',
 'White Teeth',
 'House at Riverton,The',
 'Book Thief,The',
 'Nights of Rain and Stars',
 'Ghost,The',
 'Happy Days with the Naked Chef',
 'Hunger Games,The:Hunger Games Trilogy',
 "Lost Boy,The:A Foster Child's Search for the Love of a Family",
 "Jamie's Ministry of Food:Anyone Can Learn to Cook in 24 Hours"]

In [115]:
Genre = []
for i in driver.find_elements_by_xpath('//table[@class="in-article sortable"]/tbody/tr/td[2]'):
    Genre.append(i.text)
Genre

['Da Vinci Code,The',
 'Harry Potter and the Deathly Hallows',
 "Harry Potter and the Philosopher's Stone",
 'Harry Potter and the Order of the Phoenix',
 'Fifty Shades of Grey',
 'Harry Potter and the Goblet of Fire',
 'Harry Potter and the Chamber of Secrets',
 'Harry Potter and the Prisoner of Azkaban',
 'Angels and Demons',
 "Harry Potter and the Half-blood Prince:Children's Edition",
 'Fifty Shades Darker',
 'Twilight',
 'Girl with the Dragon Tattoo,The:Millennium Trilogy',
 'Fifty Shades Freed',
 'Lost Symbol,The',
 'New Moon',
 'Deception Point',
 'Eclipse',
 'Lovely Bones,The',
 'Curious Incident of the Dog in the Night-time,The',
 'Digital Fortress',
 'Short History of Nearly Everything,A',
 'Girl Who Played with Fire,The:Millennium Trilogy',
 'Breaking Dawn',
 'Very Hungry Caterpillar,The:The Very Hungry Caterpillar',
 'Gruffalo,The',
 "Jamie's 30-Minute Meals",
 'Kite Runner,The',
 'One Day',
 'Thousand Splendid Suns,A',
 "Girl Who Kicked the Hornets' Nest,The:Millennium Trilogy",
 "Time Traveler's Wife,The",
 'Atonement',
 "Bridget Jones's Diary:A Novel",
 'World According to Clarkson,The',
 "Captain Corelli's Mandolin",
 'Sound of Laughter,The',
 'Life of Pi',
 'Billy Connolly',
 'Child Called It,A',
 "Gruffalo's Child,The",
 "Angela's Ashes:A Memoir of a Childhood",
 'Birdsong',
 'Northern Lights:His Dark Materials S.',
 'Labyrinth',
 'Harry Potter and the Half-blood Prince',
 'Help,The',
 'Man and Boy',
 'Memoirs of a Geisha',
 "No.1 Ladies' Detective Agency,The:No.1 Ladies' Detective Agency S.",
 'Island,The',
 'PS, I Love You',
 'You are What You Eat:The Plan That Will Change Your Life',
 'Shadow of the Wind,The',
 'Tales of Beedle the Bard,The',
 'Broker,The',
 "Dr. Atkins' New Diet Revolution:The No-hunger, Luxurious Weight Loss P",
 'Subtle Knife,The:His Dark Materials S.',
 'Eats, Shoots and Leaves:The Zero Tolerance Approach to Punctuation',
 "Delia's How to Cook:(Bk.1)",
 'Chocolat',
 'Boy in the Striped Pyjamas,The',
 "My Sister's Keeper",
 'Amber Spyglass,The:His Dark Materials S.',
 'To Kill a Mockingbird',
 'Men are from Mars, Women are from Venus:A Practical Guide for Improvin',
 'Dear Fatty',
 'Short History of Tractors in Ukrainian,A',
 'Hannibal',
 'Lord of the Rings,The',
 'Stupid White Men:...and Other Sorry Excuses for the State of the Natio',
 'Interpretation of Murder,The',
 'Sharon Osbourne Extreme:My Autobiography',
 'Alchemist,The:A Fable About Following Your Dream',
 "At My Mother's Knee ...:and Other Low Joints",
 'Notes from a Small Island',
 'Return of the Naked Chef,The',
 'Bridget Jones: The Edge of Reason',
 "Jamie's Italy",
 'I Can Make You Thin',
 'Down Under',
 'Summons,The',
 'Small Island',
 'Nigella Express',
 'Brick Lane',
 "Memory Keeper's Daughter,The",
 'Room on the Broom',
 'About a Boy',
 'My Booky Wook',
 'God Delusion,The',
 '"Beano" Annual,The',
 'White Teeth',
 'House at Riverton,The',
 'Book Thief,The',
 'Nights of Rain and Stars',
 'Ghost,The',
 'Happy Days with the Naked Chef',
 'Hunger Games,The:Hunger Games Trilogy',
 "Lost Boy,The:A Foster Child's Search for the Love of a Family",
 "Jamie's Ministry of Food:Anyone Can Learn to Cook in 24 Hours"]

In [117]:
### Creating dataframe
df = pd.DataFrame({})
df['Book name'] = Name
df['Author name'] = Author
df['Volumes sold'] = Volume
df['Publisher'] = Publisher
df['Genre'] = Genre
df

,Book name,Author name,Volumes sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","Da Vinci Code,The","Da Vinci Code,The","Da Vinci Code,The"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.",Harry Potter and the Deathly Hallows,Harry Potter and the Deathly Hallows,Harry Potter and the Deathly Hallows
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.",Harry Potter and the Philosopher's Stone,Harry Potter and the Philosopher's Stone,Harry Potter and the Philosopher's Stone
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.",Harry Potter and the Order of the Phoenix,Harry Potter and the Order of the Phoenix,Harry Potter and the Order of the Phoenix
4,Fifty Shades of Grey,"James, E. L.",Fifty Shades of Grey,Fifty Shades of Grey,Fifty Shades of Grey
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","Ghost,The","Ghost,The","Ghost,The"
96,Happy Days with the Naked Chef,"Oliver, Jamie",Happy Days with the Naked Chef,Happy Days with the Naked Chef,Happy Days with the Naked Chef
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","Hunger Games,The:Hunger Games Trilogy","Hunger Games,The:Hunger Games Trilogy","Hunger Games,The:Hunger Games Trilogy"
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","Lost Boy,The:A Foster Child's Search for the L...","Lost Boy,The:A Foster Child's Search for the L...","Lost Boy,The:A Foster Child's Search for the L..."
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie",Jamie's Ministry of Food:Anyone Can Learn to C...,Jamie's Ministry of Food:Anyone Can Learn to C...,Jamie's Ministry of Food:Anyone Can Learn to C...

In [118]:
###_____________________________________________________END________________________

In [119]:
driver.get('https://www.imdb.com/list/ls095964455/')

In [121]:
Name = []
for i in driver.find_elements_by_xpath('//h3[@class="lister-item-header"]/a'):
    Name.append(i.text)
len(Name)

100

In [122]:
Year = []
for i in driver.find_elements_by_xpath('//h3[@class="lister-item-header"]/span[2]'):
    Year.append(i.text)
len(Year)

100

In [123]:
Run_time = []
for i in driver.find_elements_by_xpath('//p[@class="text-muted text-small"]/span[3]'):
    Run_time.append(i.text)
len(Run_time)

100

In [124]:
Genre = []
for i in driver.find_elements_by_xpath('//p[@class="text-muted text-small"]/span[5]'):
    Genre.append(i.text)
len(Genre)

100

In [126]:
Rating = []
for i in driver.find_elements_by_xpath('//div[@class="ipl-rating-widget"]/div/span[2]'):
    Rating.append(i.text)
len(Rating)

100

In [127]:
Votes = []
for i in driver.find_elements_by_xpath('//div[@class="lister-item-content"]/p[4]/span[2]'):
    Votes.append(i.text)
len(Votes)

100

In [129]:
### Creating dataframe
df1 = pd.DataFrame({})
df1['Name'] = Name
df1['Year span'] = Year
df1['Genre'] = Genre
df1['Run time'] = Run_time
df1['Rating'] = Rating
df1['Votes'] = Votes
df1

,Name,Year span,Genre,Run time,Rating,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"1,868,522"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"903,965"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.2,"895,074"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.6,"269,345"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"229,635"
...,...,...,...,...,...,...
95,Reign,(2013–2017),"Drama, Fantasy",42 min,7.5,"45,506"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"56,378"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8,"174,494"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"36,522"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"198,360"

In [130]:
### ------------------------------------ End -----------------------------------------------------------------

In [131]:
driver.get('https://archive.ics.uci.edu/ml/index.php')
time.sleep(3)
temp = driver.find_element_by_link_text('View ALL Data Sets').get_attribute('href')
driver.get(temp)
time.sleep(3)

In [142]:
Name = []
for i in driver.find_elements_by_xpath('//p[@class="normal"]/b/a'):
    Name.append(i.text)
len(Name)

588

In [144]:
y = []
x = driver.find_elements_by_xpath('//table[@cellpadding="3"]/tbody/tr/td[2]/table[2]/tbody/tr[1]')
for i in x:
    y.append(i.text)
y

['Name\nData Types\nDefault Task\nAttribute Types\n# Instances\n# Attributes\nYear']

In [154]:
d = [i.split('\n')[0] for i in y]

In [156]:
d

['Name']

TypeError: 'builtin_function_or_method' object is not subscriptable